version: '3.8'
services:
  traefik:
    command: |
      --api
      --api.dashboard

      --entrypoints.http.address=:80
      --entrypoints.http.http.middlewares=service_error@docker
      --entrypoints.http.http.redirections.entryPoint.to=https
      --entrypoints.http.http.redirections.entryPoint.scheme=https
      --entrypoints.http.http.redirections.entryPoint.permanent=true
      --entrypoints.http.http.redirections.entryPoint.priority=500
      --entrypoints.https.address=:443
      --entrypoints.https.http.middlewares=service_error@docker
      --entrypoints.https.http.tls=true

      --providers.docker
      --providers.docker.exposedbydefault=false
      --providers.file
      --providers.file.directory=/etc/traefik/traefik.d/
      --providers.file.watch
      ${TRAEFIK_OPTIONS}
    image: traefik:v2.4
    labels:
    - traefik.enable=true
    - traefik.http.routers.api.rule=Host(`${HOSTNAME}`) && PathPrefix(`/api`) || PathPrefix(`/dashboard`)
    - traefik.http.routers.api.service=api@internal
    - traefik.http.routers.api.middlewares=api-auth,client_error

    - traefik.http.middlewares.api-auth.basicauth.usersfile=/etc/traefik/htpasswd
    - traefik.http.middlewares.redirect_https.redirectscheme.scheme=https
    - traefik.http.middlewares.redirect_https.redirectscheme.permanent=true
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - ./conf.d/traefik:/etc/traefik
    - ${LETSENCRYPT_DIR:-./conf.d/letsencrypt}:/etc/letsencrypt
    - /var/run/docker.sock:/var/run/docker.sock:ro
  fallback:
    build:
      context: ./manifest/images/fallback
    env_file: ./conf.d/fallback.env
    image: localhost/ccarney/fallback:latest
    labels:
    - traefik.enable=true
    
    - traefik.http.routers.fallback.rule=PathPrefix(`/`)
    - traefik.http.routers.fallback.priority=1
    - traefik.http.routers.fallback.middlewares=client_error

    - traefik.http.services.fallback.loadbalancer.server.port=80

    - traefik.http.middlewares.client_error.errors.status=400-499
    - traefik.http.middlewares.client_error.errors.service=fallback
    - traefik.http.middlewares.client_error.errors.query=/error/{status}.html
    - traefik.http.middlewares.service_error.errors.status=500-599
    - traefik.http.middlewares.service_error.errors.service=fallback
    - traefik.http.middlewares.service_error.errors.query=/error/{status}.html
    restart: always
    volumes:
    - ./manifest/images/fallback/pages/error:/usr/share/nginx/html/error
  certbot:
    command: renew
    expose:
    - 80
    image: certbot/certbot:latest
    labels:
    - traefik.enable=true
    - traefik.http.services.certbot.loadbalancer.server.port=80
    - traefik.http.routers.letsencrypt.rule=PathPrefix(`/.well-known/acme-challenge`)
    - traefik.http.routers.letsencrypt.priority=1000
    volumes:
    - ${LETSENCRYPT_DIR:-./conf.d/letsencrypt}:/etc/letsencrypt
networks:
  default:
    external:
      name: webproxy_nw
